import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { motion } from "framer-motion";
import {
  ArrowUpRight,
  Award,
  BookOpen,
  Briefcase,
  CheckCircle2,
  Download,
  GraduationCap,
  Lightbulb,
  Loader2,
  Mic,
  Play,
  RefreshCw,
  Share2,
  Sparkles,
  TrendingUp,
  Trophy,
  XCircle,
} from "lucide-react";
import Badge from "@/components/ui/Badge";
import Button from "@/components/ui/Button";
import { CircularProgress } from "@/components/ui/Progress";
import RadarChart from "@/components/charts/RadarChart";
import { BarChart } from "@/components/ui/Sparkline";
import EmptyState from "@/components/ui/EmptyState";
import { reportApi } from "@/services/api";
import { useToast } from "@/context/ToastContext";
import { formatDate, formatDuration, scoreColor, cn } from "@/lib/utils";

const METRIC_LABELS = {
  confidence: "Confidence",
  communication: "Communication",
  relevance: "Response relevance",
  technical: "Technical accuracy",
  fluency: "Fluency",
  pace: "Speaking speed",
};

const LEVEL_STYLE = {
  BEGINNER: {
    label: "Beginner",
    badge: "warning",
    bg: "from-rose-500/15 to-amber-500/5",
    text: "text-amber-400",
  },
  INTERMEDIATE: {
    label: "Intermediate",
    badge: "brand",
    bg: "from-brand-500/15 to-accent-500/5",
    text: "text-brand-400",
  },
  ADVANCED: {
    label: "Advanced",
    badge: "success",
    bg: "from-emerald-500/15 to-cyan-500/5",
    text: "text-emerald-400",
  },
};

export default function Report() {
  const { id } = useParams();
  const toast = useToast();
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  useEffect(() => {
    let cancelled = false;
    let interval;

    const load = async () => {
      try {
        const { report } = await reportApi.get(id);
        if (!cancelled) {
          setReport(report);
          setLoading(false);
        }
      } catch (err) {
        if (err?.response?.status === 404 && !cancelled) {
          // Report still being generated by the backend — poll for ~30s.
          interval = setInterval(async () => {
            try {
              const { report } = await reportApi.get(id);
              if (cancelled) return;
              setReport(report);
              setLoading(false);
              clearInterval(interval);
            } catch {
              // keep waiting
            }
          }, 2500);
          setTimeout(() => {
            if (loading && !cancelled) {
              clearInterval(interval);
              setLoading(false);
              toast.info(
                "Report taking longer than usual",
                "Try regenerating in a moment."
              );
            }
          }, 30_000);
        } else if (!cancelled) {
          toast.error("Couldn't load report", err?.response?.data?.title);
          setLoading(false);
        }
      }
    };

    if (id) load();
    return () => {
      cancelled = true;
      if (interval) clearInterval(interval);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  const regenerate = async () => {
    if (!id) return;
    setRefreshing(true);
    try {
      const { report } = await reportApi.regenerate(id);
      setReport(report);
      toast.success("Report regenerated");
    } catch (err) {
      toast.error("Couldn't regenerate", err?.response?.data?.title);
    } finally {
      setRefreshing(false);
    }
  };

  const downloadJson = () => {
    if (!report) return;
    const blob = new Blob([JSON.stringify(report, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `report-${report.id}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  if (!id) {
    return (
      <EmptyState
        icon={Award}
        title="Pick a session"
        description="Open any past interview from history to see its full report."
        action={
          <Link to="/app/history">
            <Button>Browse history</Button>
          </Link>
        }
      />
    );
  }

  if (loading) {
    return (
      <div className="flex min-h-[50vh] items-center justify-center">
        <div className="flex flex-col items-center gap-3">
          <Loader2 className="text-brand-400 size-8 animate-spin" />
          <p className="text-muted text-sm">Generating your performance report…</p>
          <p className="text-subtle text-xs">
            Aria is reviewing every answer with the ML scoring engine.
          </p>
        </div>
      </div>
    );
  }

  if (!report) {
    return (
      <EmptyState
        icon={Award}
        title="No report yet"
        description="This interview hasn't been scored. Try regenerating."
        action={<Button onClick={regenerate}>Generate report</Button>}
      />
    );
  }

  const level = LEVEL_STYLE[report.performanceLevel] || LEVEL_STYLE.INTERMEDIATE;
  const sessionMetrics = {
    confidence: report.confidence,
    communication: report.communication,
    relevance: report.relevance,
    technical: report.technical,
    fluency: report.fluency,
    pace: Math.min(100, Math.round((report.pace - 60) / 1.2)),
  };

  const perQuestionScores = (report.interview?.questions || []).map((q, i) => {
    const m = q.answer?.metrics;
    // A declined question is not a zero-scoring answer — it is an unanswered
    // question, and the chart must not present the two as the same thing.
    if (q.answer?.skipped || q.answer?.intent === "dont_know") {
      return { label: `Q${i + 1}`, value: 0, skipped: true };
    }
    if (!m) return { label: `Q${i + 1}`, value: 0, unscored: true };
    const avg = Math.round(
      ((m.confidence ?? 0) +
        (m.communication ?? 0) +
        (m.relevance ?? 0) +
        (m.technical ?? 0) +
        (m.fluency ?? 0)) /
        5
    );
    return { label: `Q${i + 1}`, value: avg, domain: q.domain };
  });

  // Session measurements behind every score, written by the ML report generator.
  const analytics = report.analytics || {};
  const byDomain = Array.isArray(analytics.byDomain) ? analytics.byDomain : [];
  const skippedQuestions = Array.isArray(analytics.skippedQuestions)
    ? analytics.skippedQuestions
    : [];

  const duration =
    report.interview?.startedAt && report.interview?.endedAt
      ? Math.round(
          (new Date(report.interview.endedAt).getTime() -
            new Date(report.interview.startedAt).getTime()) /
            1000
        )
      : null;

  const resources = Array.isArray(report.resources) ? report.resources : [];

  return (
    <div className="space-y-8">
      {/* Hero */}
      <motion.div
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        className="from-brand-600/30 via-brand-500/10 to-accent-500/10 border-brand-500/30 relative overflow-hidden rounded-3xl border bg-gradient-to-br p-6 sm:p-8"
      >
        <div className="absolute -right-12 -top-12 size-60 rounded-full bg-brand-500/30 blur-3xl" />
        <div className="grid items-center gap-6 lg:grid-cols-12">
          <div className="lg:col-span-8">
            <div className="flex flex-wrap items-center gap-2">
              <Badge variant="brand" icon={Sparkles}>
                Session report · §3.3
              </Badge>
              <Badge variant="outline">{report.interview?.category}</Badge>
              <Badge variant="outline">{report.interview?.difficulty}</Badge>
              <Badge variant={level.badge} icon={GraduationCap}>
                {level.label}
              </Badge>
            </div>
            <h1 className="font-display text-default mt-3 text-3xl font-bold sm:text-4xl">
              {report.interview?.role}
            </h1>
            <p className="text-muted mt-1 text-sm">
              {formatDate(report.generatedAt)}
              {duration ? ` · ${formatDuration(duration)}` : ""} ·{" "}
              {report.interview?.questions?.length ?? 0} questions
            </p>
            <div className="mt-6 flex flex-wrap gap-2">
              <Button leftIcon={Download} onClick={downloadJson}>
                Download report
              </Button>
              <Button
                variant="glass"
                leftIcon={RefreshCw}
                onClick={regenerate}
                loading={refreshing}
              >
                Regenerate
              </Button>
              <Button variant="glass" leftIcon={Share2}>
                Share
              </Button>
              <Link to={`/app/interview`}>
                <Button variant="glass" leftIcon={Play}>
                  New interview
                </Button>
              </Link>
            </div>
          </div>

          <div className="lg:col-span-4">
            <div className="flex items-center justify-center gap-6">
              <CircularProgress value={report.overallScore} size={150}>
                <div className="flex flex-col items-center">
                  <span className="font-display text-default text-4xl font-bold">
                    {report.overallScore}
                  </span>
                  <span className="text-subtle text-[10px] uppercase tracking-wider">
                    Overall
                  </span>
                </div>
              </CircularProgress>
              <div className="space-y-1.5">
                <Stat
                  icon={GraduationCap}
                  label="Performance"
                  value={level.label}
                  tone={level.text}
                />
                <Stat
                  icon={Trophy}
                  label="Words spoken"
                  value={wordCount(report)}
                />
                <Stat icon={Mic} label="Answers" value={`${perQuestionScores.length}`} />
              </div>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Performance level callout */}
      <div
        className={cn(
          "border-token relative overflow-hidden rounded-3xl border bg-gradient-to-br p-5",
          level.bg
        )}
      >
        <div className="flex items-start gap-3">
          <div
            className={cn(
              "from-brand-500 to-accent-500 grid size-10 shrink-0 place-items-center rounded-xl bg-gradient-to-br text-white"
            )}
          >
            <GraduationCap className="size-5" />
          </div>
          <div>
            <p className="text-default text-sm font-semibold">
              ML-classified performance level:{" "}
              <span className={level.text}>{level.label}</span>
            </p>
            <p className="text-muted mt-1 text-sm">
              {report.performanceLevel === "ADVANCED"
                ? "You're interview-ready. Focus on senior-level signaling and sharp closes."
                : report.performanceLevel === "INTERMEDIATE"
                ? "Solid foundations. Drill the weak metrics below to break into the advanced band."
                : "Beginner band — keep practising. Aim for clarity and pacing first; depth will follow."}
            </p>
          </div>
        </div>
      </div>

      {/* Six-metric breakdown — §3.3 */}
      <div className="grid gap-6 lg:grid-cols-3">
        <div className="bg-surface border-token rounded-3xl border p-6 lg:col-span-2">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-default text-lg font-semibold">
                6-metric breakdown
              </h2>
              <p className="text-muted text-xs">
                Confidence · Communication · Relevance · Technical · Fluency · Pace
              </p>
            </div>
            <Badge variant="success" icon={TrendingUp}>
              {report.overallScore}/100
            </Badge>
          </div>
          <div className="mt-5 grid items-center gap-6 sm:grid-cols-2">
            <RadarChart
              data={Object.entries(sessionMetrics).map(([k, v]) => ({
                label: METRIC_LABELS[k] || k,
                value: v,
              }))}
            />
            <div className="space-y-3">
              {Object.entries(METRIC_LABELS).map(([k, label]) => {
                const raw = report[k];
                const value = k === "pace" ? raw : raw;
                return (
                  <MetricRow
                    key={k}
                    label={label}
                    value={value}
                    suffix={k === "pace" ? " wpm" : "%"}
                    bar={k === "pace" ? Math.min(100, Math.round((raw - 60) / 1.2)) : raw}
                  />
                );
              })}
            </div>
          </div>
        </div>

        <div className="bg-surface border-token rounded-3xl border p-6">
          <h2 className="text-default text-lg font-semibold">
            Question-by-question
          </h2>
          <p className="text-muted text-xs">
            Average across the 5 quality metrics per answer.
          </p>
          <div className="mt-5">
            {perQuestionScores.length === 0 ? (
              <p className="text-subtle text-sm italic">No answers recorded.</p>
            ) : (
              <BarChart height={180} data={perQuestionScores} />
            )}
          </div>
        </div>
      </div>

      {/*
        The evidence behind the scores. Every strength and weakness below is
        derived from these measurements, so showing them lets the candidate see
        the working rather than take the findings on trust.
      */}
      {analytics.answerCount > 0 && (
        <div className="bg-surface border-token rounded-3xl border p-6">
          <div className="mb-4 flex items-center justify-between">
            <h3 className="text-default text-lg font-semibold">
              What was measured
            </h3>
            <Badge variant="brand">
              {analytics.answeredCount}/{analytics.answerCount} answered
            </Badge>
          </div>

          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <Measure
              label="Questions engaged"
              value={`${Math.round((analytics.coverage ?? 0) * 100)}%`}
              hint={
                analytics.skippedCount
                  ? `${analytics.skippedCount} declined`
                  : "none declined"
              }
            />
            <Measure
              label="Average answer"
              value={`${analytics.avgWords ?? 0} words`}
              hint="60–120 is the target for technical answers"
            />
            <Measure
              label="Concrete examples"
              value={`${analytics.concreteExamples ?? 0} of ${analytics.answerCount}`}
              hint="answers citing a project, number or example"
            />
            <Measure
              label="Filler rate"
              value={`${analytics.avgFillerRate ?? 0}%`}
              hint="under 3% reads as fluent"
            />
          </div>

          {/* Which topic areas were strong and which were weak. */}
          {byDomain.length > 0 && (
            <div className="mt-6">
              <p className="text-subtle mb-3 text-[10px] uppercase tracking-wider">
                Technical accuracy by topic
              </p>
              <div className="space-y-2">
                {byDomain.map((d) => (
                  <div key={d.domain} className="flex items-center gap-3">
                    <span className="text-muted w-44 shrink-0 truncate text-xs">
                      {d.domain}
                    </span>
                    <div className="bg-surface-2 h-2 flex-1 overflow-hidden rounded-full">
                      <div
                        className={cn(
                          "h-full rounded-full",
                          (d.technical ?? 0) >= 70
                            ? "bg-emerald-500"
                            : (d.technical ?? 0) >= 50
                              ? "bg-amber-500"
                              : "bg-rose-500"
                        )}
                        style={{ width: `${Math.max(2, d.technical ?? 0)}%` }}
                      />
                    </div>
                    <span className="text-default w-16 shrink-0 text-right text-xs font-semibold">
                      {d.technical == null ? "—" : Math.round(d.technical)}
                    </span>
                    <span className="text-subtle w-14 shrink-0 text-right text-[10px]">
                      {d.questions} q
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Declined questions, named — these are the concrete study targets. */}
          {skippedQuestions.length > 0 && (
            <div className="mt-6 rounded-2xl border border-amber-500/30 bg-amber-500/5 p-4">
              <p className="text-default mb-2 text-xs font-semibold">
                Questions you declined — start here
              </p>
              <ul className="space-y-1.5">
                {skippedQuestions.map((q) => (
                  <li key={q.ordinal} className="text-muted text-xs leading-relaxed">
                    <span className="text-amber-400">•</span> {q.question}
                    {q.domain && (
                      <span className="text-subtle"> · {q.domain}</span>
                    )}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </div>
      )}

      {/* Strengths / weaknesses */}
      <div className="grid gap-6 lg:grid-cols-2">
        <List
          title="Strengths"
          tone="emerald"
          icon={CheckCircle2}
          items={report.strengths || []}
        />
        <List
          title="Areas to improve"
          tone="rose"
          icon={XCircle}
          items={report.weaknesses || []}
        />
      </div>

      {/* Coach note + suggestions */}
      <div className="from-amber-400/15 to-brand-500/10 border-amber-400/30 relative overflow-hidden rounded-3xl border bg-gradient-to-br p-6">
        <Lightbulb className="text-amber-400 absolute right-6 top-6 size-7" />
        <Badge variant="warning" icon={Lightbulb}>
          Coach suggestions · §3.4
        </Badge>
        <ul className="mt-4 space-y-2.5">
          {(report.suggestions || []).map((s, i) => (
            <li key={i} className="text-default flex items-start gap-2.5 text-sm">
              <span className="text-amber-400 mt-1 size-1.5 shrink-0 rounded-full bg-current" />
              {s}
            </li>
          ))}
        </ul>
      </div>

      {/* Learning resources — §3.4 */}
      {resources.length > 0 && (
        <div className="bg-surface border-token rounded-3xl border p-6">
          <div className="mb-5 flex items-center justify-between">
            <div>
              <h2 className="text-default text-lg font-semibold">
                Recommended learning resources
              </h2>
              <p className="text-muted text-xs">
                Curated to close your weakest metrics.
              </p>
            </div>
            <Badge variant="brand">AI curated</Badge>
          </div>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {resources.map((r, i) => (
              <a
                key={`${r.title}-${i}`}
                href={r.url || "#"}
                target={r.url ? "_blank" : undefined}
                rel="noreferrer"
                className="group bg-surface-2 border-token hover:border-brand-500/40 rounded-2xl border p-4 transition"
              >
                <div className="flex items-start justify-between">
                  <div className="from-brand-500/15 to-accent-500/15 text-brand-400 grid size-9 place-items-center rounded-xl bg-gradient-to-br">
                    <BookOpen className="size-4.5" />
                  </div>
                  <ArrowUpRight className="text-subtle group-hover:text-brand-400 size-4 transition" />
                </div>
                <p className="text-default mt-3 text-sm font-semibold">{r.title}</p>
                {r.description && (
                  <p className="text-muted mt-1 text-xs">{r.description}</p>
                )}
                <p className="text-subtle mt-2 text-[11px] uppercase tracking-wider">
                  {r.type}
                </p>
              </a>
            ))}
          </div>
        </div>
      )}

      {/* Job matches — §3.5 */}
      {report.jobMatches?.length > 0 && (
        <div className="bg-surface border-token rounded-3xl border p-6">
          <div className="mb-5 flex items-center justify-between">
            <div>
              <h2 className="text-default text-lg font-semibold">
                Matching job roles · §3.5
              </h2>
              <p className="text-muted text-xs">
                Built from your CV skills + this interview's performance.
              </p>
            </div>
            <Link
              to="/app/jobs"
              className="text-brand-400 hover:text-brand-300 inline-flex items-center gap-1 text-sm font-semibold"
            >
              All matches <ArrowUpRight className="size-4" />
            </Link>
          </div>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {report.jobMatches.slice(0, 6).map((m) => (
              <div
                key={m.id}
                className="bg-surface-2 border-token rounded-2xl border p-4"
              >
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <p className="text-default text-sm font-semibold">
                      {m.job.title}
                    </p>
                    <p className="text-subtle text-xs">
                      {m.job.company} · {m.job.location || "Remote"}
                    </p>
                  </div>
                  <span className={`font-display text-xl font-bold ${scoreColor(m.matchScore)}`}>
                    {Math.round(m.matchScore)}
                  </span>
                </div>
                {Array.isArray(m.skillGaps) && m.skillGaps.length > 0 && (
                  <div className="mt-3">
                    <p className="text-subtle text-[10px] uppercase tracking-wider">
                      Skill gaps
                    </p>
                    <div className="mt-1 flex flex-wrap gap-1">
                      {m.skillGaps.slice(0, 4).map((s) => (
                        <span
                          key={s}
                          className="rounded-full border border-rose-500/30 bg-rose-500/10 px-2 py-0.5 text-[10px] font-medium text-rose-400"
                        >
                          {s}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

function Stat({ icon: Icon, label, value, tone = "text-brand-400" }) {
  return (
    <div className="flex items-center gap-3">
      <Icon className={cn("size-5", tone)} />
      <div>
        <p className="text-subtle text-[10px] font-semibold uppercase tracking-wider">
          {label}
        </p>
        <p className="text-default text-sm font-bold">{value}</p>
      </div>
    </div>
  );
}

function MetricRow({ label, value, suffix = "%", bar }) {
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-sm">
        <span className="text-default font-medium">{label}</span>
        <span className={`font-semibold ${scoreColor(bar ?? value)}`}>
          {value}
          {suffix}
        </span>
      </div>
      <div className="bg-surface-2 border-token h-1.5 overflow-hidden rounded-full border">
        <motion.div
          initial={{ width: 0 }}
          whileInView={{ width: `${Math.max(0, Math.min(100, bar ?? value))}%` }}
          viewport={{ once: true }}
          transition={{ duration: 0.9, ease: "easeOut" }}
          className="from-brand-400 to-accent-400 h-full bg-gradient-to-r"
        />
      </div>
    </div>
  );
}

function List({ title, tone, icon: Icon, items }) {
  const tones = {
    emerald: "from-emerald-400/15 to-emerald-500/5 text-emerald-400",
    rose: "from-rose-400/15 to-rose-500/5 text-rose-400",
  };
  return (
    <div className="bg-surface border-token rounded-3xl border p-6">
      <div className="flex items-center gap-3">
        <div className={`grid size-10 place-items-center rounded-xl bg-gradient-to-br ${tones[tone]}`}>
          <Icon className="size-4.5" />
        </div>
        <h3 className="text-default text-base font-semibold">{title}</h3>
      </div>
      {items.length === 0 ? (
        <p className="text-subtle mt-4 text-sm italic">Nothing here yet.</p>
      ) : (
        <ul className="mt-4 space-y-3">
          {items.map((i, k) => (
            <li key={`${i}-${k}`} className="flex items-start gap-2.5">
              <span
                className={cn(
                  "mt-1 size-1.5 shrink-0 rounded-full",
                  tone === "emerald" ? "bg-emerald-400" : "bg-rose-400"
                )}
              />
              <span className="text-default text-sm">{i}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function wordCount(report) {
  const qs = report.interview?.questions || [];
  let total = 0;
  for (const q of qs) {
    const t = q.answer?.transcript;
    if (t) total += t.trim().split(/\s+/).filter(Boolean).length;
  }
  return total.toLocaleString();
}

function Measure({ label, value, hint }) {
  return (
    <div className="bg-surface-2 border-token rounded-2xl border p-4">
      <p className="text-subtle text-[10px] uppercase tracking-wider">{label}</p>
      <p className="text-default mt-1 text-lg font-bold">{value}</p>
      <p className="text-muted mt-1 text-[10px] leading-snug">{hint}</p>
    </div>
  );
}
